# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'

defaults: &defaults


development:
  database: deputi_development
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password:
  host: localhost
  port: 5432
  # <<: *defaults


test:
  database: deputi_test
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password:
  host: localhost
  port: 5432
  <<: *defaults

# production:
#   database: contact_book_production
#   <<: *defaults
